# Generated by Django 3.2.4 on 2022-04-26 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=400, unique=True),
        ),
    ]
